name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8  # Use the Python version matching your Lambda function

    - name: Install dependencies
      run: |
        pip install aws-sam-cli

    - name: Build SAM Application
      run: |
        sam build -t backend/template.yaml  # Make sure the path is correct here

    - name: Deploy SAM Application
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        sam deploy \
          --stack-name trending-media-headlines-stack \  # Name of your CloudFormation stack
          --capabilities CAPABILITY_IAM \  # Required to allow SAM to create IAM roles
          --parameter-overrides NewsApiKey=${{ secrets.NEWS_API_KEY }} \  # Pass parameters if needed
          --no-confirm-changeset \  # Skip confirmation prompts
          --no-fail-on-empty-changeset  # Prevent failure if no changes detected